import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api/apiClient";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

export interface Patient {
  id: string;
  first_name: string;
  last_name: string;
  document_type: string;
  document_number: string;
  birth_date: string | null;
  gender: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  city: string | null;
  occupation: string | null;
  marital_status: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  insurance_provider: string | null;
  insurance_policy_number: string | null;
  blood_type: string | null;
  allergies: string[] | null;
  clinical_history_code: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export type PatientInsert = Omit<Patient, 'id' | 'clinical_history_code' | 'created_at' | 'updated_at'>;
export type PatientUpdate = Partial<PatientInsert>;

// Fetch all patients
export function usePatients() {
  return useQuery({
    queryKey: ["patients"],
    queryFn: async () => {
      const { data, error } = await api
        .from<Patient>("patients")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as Patient[];
    },
  });
}

// Fetch single patient by ID
export function usePatient(id: string | null) {
  return useQuery({
    queryKey: ["patient", id],
    queryFn: async () => {
      if (!id) return null;

      const { data, error } = await api
        .from<Patient>("patients")
        .select("*")
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as Patient;
    },
    enabled: !!id,
  });
}

// Create new patient with automatic clinical history
export function useCreatePatient() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (patient: PatientInsert) => {
      // Create patient (clinical_history_code is auto-generated by trigger)
      const { data: newPatient, error: patientError } = await api
        .from<Patient>("patients")
        .insert(patient)
        .select()
        .single();

      if (patientError) throw patientError;
      if (!newPatient) throw new Error("No patient data returned");

      // Create initial clinical history entry
      const { error: historyError } = await api
        .from("patient_health_history")
        .insert({
          patient_id: newPatient.id,
          diagnosis: "Historia clínica iniciada",
          treatment: null,
          notes: `Paciente registrado el ${new Date().toLocaleDateString('es-CO')}. Código de historia: ${newPatient.clinical_history_code}`,
          created_by: user?.id,
        });

      if (historyError) {
        console.error("Error creating initial clinical history:", historyError);
      }

      return newPatient;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["patients"] });
      queryClient.invalidateQueries({ queryKey: ["clinical-history"] });
      toast({
        title: "Paciente creado",
        description: `Historia clínica ${data.clinical_history_code} asignada.`,
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "No se pudo crear el paciente. " + error.message,
        variant: "destructive",
      });
    },
  });
}

// Update patient
export function useUpdatePatient() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...updates }: { id: string } & PatientUpdate) => {
      const { data, error } = await api
        .from<Patient>("patients")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["patients"] });
      toast({
        title: "Paciente actualizado",
        description: "Los datos han sido guardados.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "No se pudo actualizar el paciente. " + error.message,
        variant: "destructive",
      });
    },
  });
}

// Delete patient
export function useDeletePatient() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await api
        .from("patients")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["patients"] });
      toast({
        title: "Paciente eliminado",
        description: "El paciente ha sido eliminado del sistema.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "No se pudo eliminar el paciente. " + error.message,
        variant: "destructive",
      });
    },
  });
}

// Search patients
export function useSearchPatients(searchTerm: string) {
  return useQuery({
    queryKey: ["patients", "search", searchTerm],
    queryFn: async () => {
      if (!searchTerm || searchTerm.length < 2) return [];

      const { data, error } = await api
        .from<Patient>("patients")
        .select("id, first_name, last_name, document_number, phone")
        .or([
          `first_name.ilike.%${searchTerm}%`,
          `last_name.ilike.%${searchTerm}%`,
          `document_number.ilike.%${searchTerm}%`
        ])
        .limit(10);

      if (error) throw error;
      return data;
    },
    enabled: searchTerm.length >= 2,
  });
}
